### ISSUE TITLE
acars2 validation fails

### ISSUE THREAD

**Issue by tfcollins** [gnieboer/GNURadio_Windows_Build_Scripts#35]
From master with a Release build and using built dependencies acars2 OOT fails to validate

**Comment by Siebje** [comment]
I found the same thing, and it is due to a problem with doxygen or a compatibility issue between CMake and doxygen (you can find this by inspecting the log from the acars2 build, it will show an Access Violation, which is super strange). I tried building on a different machine, and on that one doxygen actually crashes differently but I can choose to close it and the build will continue. Maybe using a different (older) version of doxygen does the trick?

**Comment by gnieboer** [comment]
Interesting.  I will take a look after I get a 3.8 version out the door

**Comment by tfcollins** [comment]
Might be awhile. OOTs are still broken in 3.8

**Comment by gnieboer** [comment]
I was not able to duplicate, however I do have an ancient version of doxygen installed.  Can you tell me what version you guys have?

**Comment by Siebje** [comment]
From what I can see, I was using 1.8.11 or 1.8.14. In the end I spent so much time getting the project to build (with a very old UHD version) that I decided to implement my own UHD driver :)

**Comment by gnieboer** [comment]
Closing this issue.  As mentioned, this was likely a host machine configuration issue.  

I have now published an AWS AMI that is "guaranteed" to be compatible with the scripts and so I recommend to use that AMI to generate the installers to avoid those issues.
